### ISSUE TITLE
JetBrain branch: No instructions on how to include listeditor.html

### ISSUE THREAD

**Issue by macdonst** [imhotep/PGDayEUWs2016#3]
When running through the instructions https://github.com/imhotep/PGDayEUWs2016/blob/jetbrains/android/README.md I didn't see any mention of how/when to include listeditor.html. When you run through the entire tutorial you get to the end and the web view fails to load listeditor.html when you run the app.

**Comment by imhotep** [comment]
Fixed. Thanks!
