### ISSUE TITLE
Error: You need to install NodeJS and plugman...

### ISSUE THREAD

**Issue by mwbrooks** [imhotep/PGDayEUWs2016#4]
I cannot get past [Step 2](https://github.com/imhotep/PGDayEUWs2016/tree/jetbrains/android/step1-setup-cordova-in-native-project) when installing a plugin from npm.

## Step 2.6 Go to Tools > PhoneGap > Install Plugin from npm

I receive the following error when installing a plugin:

> **Error**
> You need to install NodeJS and plugman in order to be able to use plugins. If you are on Mac OS X make sure you run the following: `sudo launchctl config user path $PATH`

NodeJS is installed:

```
$ node -v
v6.5.0
```

npm is installed:

```
$ npm -v
3.10.3
```

Plugman is installed:

```
$ plugman -v
1.4.0
```

I execute the following command `sudo launchctl config user path $PATH`:

```
$ sudo launchctl config user path $PATH
Password:
Configuration applied. You must reboot for changes to take effect.
```

I restart my computer.

Android Studio produces the same error:

![android-studio-error](https://cloud.githubusercontent.com/assets/21328/20636577/01b99b44-b324-11e6-837e-ff08707d0db1.gif)
 
I've restarted Android Studio multiple times and it continues to produce the same error.

/cc @macdonst

**Comment by macdonst** [comment]
@mwbrooks how do you launch Android Studio? From the Application folder or from the command line?

**Comment by mwbrooks** [comment]
@macdonst wow, I never even considered that. I launched it from the Application folder... like any normal application.

I just tried launching Android Studio from the command-line and it worked:

```
$ open /Applications/Android\ Studio.app
```

![image](https://cloud.githubusercontent.com/assets/21328/20636861/f12e77da-b329-11e6-8fa3-5ce3dedc6e6a.png)

I don't feel like this is acceptable unless it's the norm for Android Studio developers to open Android Studio from the command-line.

**Comment by macdonst** [comment]
@mwbrooks there is some sort of screwyness going on with envars being passed to Android Studio depending on how it is opened. We should still look at it more closely.

**Comment by imhotep** [comment]
@mwbrooks is it still not working when launched from `Applications` folder? I don't have any issues personally. It's related to Environment Variables indeed.

**Comment by mwbrooks** [comment]
@imhotep yea, unfortunately it requires me to open it via the command-line otherwise the plugin commands fail. If you're not having the issue, then there is hope. Is there an ENV that I can configure inside Android Studio?
